validation: sovereign
version: 1
accounts:
    - name: alice
      coins:
        - 20000urise
        - 200000000uvrise
        - 200000000uusdrise
    - name: bob
      coins:
        - 10000urise
        - 100000000uvrise
        - 100000000uusdrise
faucet:
    name: bob
    coins:
        - 5urise
        - 100000uvrise
        - 100000000uusdrise
client:
    typescript:
        path: ts-client
    openapi:
        path: docs/static/openapi.json
validators:
    - name: alice
      bonded: 100000000uvrise
    - name: validator1
      bonded: 100000000uvrise
    - name: validator2
      bonded: 200000000uvrise
    - name: validator3
      bonded: 300000000uvrise
